# Generated by Django 3.0.8 on 2020-10-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20201003_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
