# Generated by Django 3.0.8 on 2020-10-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_party_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='rsvp_responded',
            field=models.BooleanField(default=False),
        ),
    ]
