# Generated by Django 3.0.8 on 2020-10-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_auto_20201004_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='dietary_requirements',
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary_requirements',
            field=models.ManyToManyField(to='wedding.DietaryReq'),
        ),
    ]
