# Generated by Django 3.0.8 on 2020-10-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_auto_20201004_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='wants_hotel_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='wants_hotel_room_day_before',
            field=models.BooleanField(default=False),
        ),
    ]
