# Generated by Django 3.0.8 on 2021-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20201004_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='attending',
        ),
        migrations.AddField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='dietary_requirements_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
