# Generated by Django 3.0.8 on 2021-02-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_party_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary_requirements',
            field=models.ManyToManyField(blank=True, to='wedding.DietaryReq'),
        ),
    ]
