# Generated by Django 3.0.8 on 2021-02-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_auto_20210217_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
