# Generated by Django 3.0.8 on 2021-02-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0012_guest_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
