# Generated by Django 3.1.6 on 2021-03-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_guest_is_plus_one'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['sequence', 'created']},
        ),
        migrations.AlterField(
            model_name='guest',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
