# Generated by Django 3.1.6 on 2021-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_auto_20210321_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
