# Generated by Django 3.1.12 on 2021-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0015_guest_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert',
            name='exclude_dietary_class',
        ),
        migrations.RemoveField(
            model_name='main',
            name='exclude_dietary_class',
        ),
        migrations.RemoveField(
            model_name='starter',
            name='exclude_dietary_class',
        ),
        migrations.AddField(
            model_name='dessert',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='starter',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
