# Generated by Django 3.0.8 on 2020-08-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_connection_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
