# Generated by Django 3.0.8 on 2020-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='last_pulled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
