# Generated by Django 3.0.8 on 2020-08-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200809_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='targettype',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
