# Generated by Django 3.0.8 on 2020-08-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_targettype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
