# Generated by Django 3.0.8 on 2020-08-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_activitytype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengetarget',
            name='field',
            field=models.CharField(default='field', max_length=255),
            preserve_default=False,
        ),
    ]
