# Generated by Django 3.0.8 on 2020-08-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_challengetarget_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetarget',
            name='field',
        ),
        migrations.AddField(
            model_name='targettype',
            name='field',
            field=models.CharField(default='field', max_length=255),
            preserve_default=False,
        ),
    ]
