# Generated by Django 3.0.8 on 2020-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200810_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
