# Generated by Django 3.0.8 on 2020-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_activity_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='raw_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
