# Generated by Django 3.0.8 on 2020-08-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200816_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='moving_duration_seconds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
