# Generated by Django 3.0.8 on 2020-08-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20200819_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='targettracking',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.ChallengeTarget'),
            preserve_default=False,
        ),
    ]
