# Generated by Django 3.0.8 on 2020-08-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200821_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Connection'),
        ),
        migrations.AddField(
            model_name='activitystream',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Activity'),
            preserve_default=False,
        ),
    ]
