# Generated by Django 3.0.8 on 2020-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20200821_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtype',
            name='display_graph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamtype',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
