# Generated by Django 3.0.8 on 2020-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200821_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtype',
            name='rgb',
            field=models.CharField(default=(255, 255, 255), max_length=255),
            preserve_default=False,
        ),
    ]
