# Generated by Django 3.0.8 on 2020-08-26 22:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_streamtype_rgb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('timestamp', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feels_like', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pressure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dew_point', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clouds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visibility', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wind_deg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
