# Generated by Django 3.0.8 on 2021-03-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_servicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
