# Generated by Django 3.0.8 on 2020-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
