# Generated by Django 3.0.8 on 2021-03-07 23:46

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20210307_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.TimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
