# Generated by Django 3.0.8 on 2021-03-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
    ]
