# Generated by Django 3.0.8 on 2021-03-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20210308_0018'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='unique_keyword',
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('keyword', 'recipe'), name='unique_keyword'),
        ),
    ]
