# Generated by Django 3.0.8 on 2021-03-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20210308_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='importance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
