# Generated by Django 3.0.8 on 2021-03-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='unique_keyword',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='recipe',
        ),
        migrations.AddField(
            model_name='keyword',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Product'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('keyword', 'product'), name='unique_keyword'),
        ),
    ]
