# Generated by Django 3.0.8 on 2021-03-08 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20210308_0048'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='unique_keyword',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='product',
        ),
        migrations.AddField(
            model_name='keyword',
            name='importance',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('keyword', 'recipe'), name='unique_keyword'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
