# Generated by Django 3.0.8 on 2021-03-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_auto_20210308_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cookbook.Tag'),
        ),
    ]
