# Generated by Django 3.1.6 on 2021-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_auto_20210310_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
