# Generated by Django 3.1.6 on 2021-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_auto_20210424_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
